Sstoolkit 13 merge branch
nordic-institute/X-Road-Security-Server-toolkit pull request #9
Opened 2020-11-27 08:52 UTC by unserializable

* does the selection of single timestamping service, if approved services exist and are not configured ``init``
* contains bonus of listing approved / configured timestamping services, they are both for easing demo and to get discussion going of how we approach this separation (e.g. subcommand name difference like in bonus, subcommand arguments, even something else)

2020-11-27 10:02 UTC, bertvi requested changes
____________________________________________________________________________________________ [pylint] xrdsst/controllers/token.py _____________________________________________________________________________________________
R:  1, 0: Similar lines in 2 files
==tests.unit.test_timestamp:26
==tests.unit.test_token:84
              'owner_member_class': 'VOG',
              'owner_member_code': '4321',
              'security_server_code': 'SS3',
              'software_token_id': '0',
              'software_token_pin': '1122'}]}
 (duplicate-code)
R:  1, 0: Similar lines in 2 files
==tests.unit.test_timestamp:19
==tests.unit.test_token:77
    ss_config = {
        'logging': [{'file': '/tmp/xrdsst_test_token_log', 'level': 'INFO'}],
        'security-server':
            [{'name': 'ssX',
              'url': 'https://non.existing.url.blah:8999/api/v1',
              'api_key': 'X-Road-apikey token=api-key', (duplicate-code)
=================================================================================================== short test summary info ===================================================================================================
FAILED tests/unit/test_timestamp.py::PYLINT
FAILED xrdsst/controllers/timestamp.py::PYLINT
FAILED xrdsst/controllers/token.py::PYLINT

2020-11-27 10:02 UTC, bertvi commented on tests/unit/test_timestamp.py
> +    ss_config = {
Probably it would be possible to take this ss_config from the "TestBaseController" ?

2020-11-27 10:02 UTC, bertvi commented on xrdsst/controllers/timestamp.py
> +import logging
__________________________________________________________________________________________ [pylint] xrdsst/controllers/timestamp.py ___________________________________________________________________________________________
E:  5, 0: Attempted relative import beyond top-level package (relative-beyond-top-level)
E:  8, 0: Attempted relative import beyond top-level package (relative-beyond-top-level)
E: 10, 0: Attempted relative import beyond top-level package (relative-beyond-top-level)
E: 11, 0: Attempted relative import beyond top-level package (relative-beyond-top-level)
C: 85, 8: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
R: 88, 4: Method could be a function (no-self-use)
W: 92,71: Unused argument 'security_server' (unused-argument)
W: 95,62: Unused argument 'security_server' (unused-argument)
C:117,15: Comparison should be excn.status == 409 (misplaced-comparison-constant)
W:122,16: Use lazy % formatting in logging functions (logging-not-lazy)
C:  6, 0: first party import "from xrdsst.api_client.api_client import ApiClient" should be placed before "from .base import BaseController" (wrong-import-order)
C:  7, 0: first party import "from xrdsst.resources.texts import texts" should be placed before "from .base import BaseController" (wrong-import-order)
C:  9, 0: first party import "from xrdsst.api.system_api import SystemApi" should be placed before "from .base import BaseController" (wrong-import-order)

2020-11-27 10:02 UTC, bertvi commented on tests/unit/test_timestamp.py
> +import unittest
____________________________________________________________________________________________ [pylint] tests/unit/test_timestamp.py ____________________________________________________________________________________________
C: 35, 0: Line too long (126/100) (line-too-long)
C: 53, 0: Line too long (126/100) (line-too-long)
C: 55, 0: Line too long (102/100) (line-too-long)
C: 64, 0: Line too long (126/100) (line-too-long)
C: 69, 0: Line too long (123/100) (line-too-long)
C: 71, 0: Trailing newlines (trailing-newlines)
R: 33, 4: Method could be a function (no-self-use)
R: 42, 4: Method could be a function (no-self-use)
R: 51, 4: Method could be a function (no-self-use)
R: 62, 4: Method could be a function (no-self-use)
C:  3, 0: standard import "from unittest import mock, TestCase" should be placed before "import urllib3" (wrong-import-order)

2020-11-27 10:04 UTC, bertvi commented
Please also update Changelog and User Guide

2020-11-27 10:13 UTC, bertvi commented
I re-initialized my local security servers with the bash script, then ran xrdsst init, xrdsst token list, xrdsst token init, xrdsst timestamp list-approved and xrdsst timestamp list-configured, all of these worked fine. But when I finally ran xrdsst timestamp init, this resulted in a exception:

ss3 Timestamping service initialization configuration failure (403)
Reason: 
HTTP response headers: HTTPHeaderDict({'x-road-ui-correlation-id': 'b8d9ef74781374b2', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Frame-Options': 'DENY', 'Content-Security-Policy': "default-src 'none'", 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 27 Nov 2020 10:11:02 GMT'})
HTTP response body: {"status":403}

ss4 Timestamping service initialization configuration failure (403)
Reason: 
HTTP response headers: HTTPHeaderDict({'x-road-ui-correlation-id': '779d41c7f37be08c', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Frame-Options': 'DENY', 'Content-Security-Policy': "default-src 'none'", 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 27 Nov 2020 10:11:02 GMT'})
HTTP response body: {"status":403}

2020-11-27 10:29 UTC, unserializable commented
> I re-initialized my local security servers with the bash script, then ran xrdsst init, xrdsst token list, xrdsst token init, xrdsst timestamp list-approved and xrdsst timestamp list-configured, all of these worked fine. But when I finally ran xrdsst timestamp init, this resulted in a exception:
> 
> ss3 Timestamping service initialization configuration failure (403)
> Reason:
> HTTP response headers: HTTPHeaderDict({'x-road-ui-correlation-id': 'b8d9ef74781374b2', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Frame-Options': 'DENY', 'Content-Security-Policy': "default-src 'none'", 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 27 Nov 2020 10:11:02 GMT'})
> HTTP response body: {"status":403}
> 

This occurs when there is no permissions for initialization (in this case, security officer role should be sufficient). We do not have any general way to approach this currently -- global response handling and global exception handling should be addressed together in the pipeline.

2020-11-27 10:50 UTC, bertvi commented
> > I re-initialized my local security servers with the bash script, then ran xrdsst init, xrdsst token list, xrdsst token init, xrdsst timestamp list-approved and xrdsst timestamp list-configured, all of these worked fine. But when I finally ran xrdsst timestamp init, this resulted in a exception:
> > ss3 Timestamping service initialization configuration failure (403)
> > Reason:
> > HTTP response headers: HTTPHeaderDict({'x-road-ui-correlation-id': 'b8d9ef74781374b2', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Frame-Options': 'DENY', 'Content-Security-Policy': "default-src 'none'", 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 27 Nov 2020 10:11:02 GMT'})
> > HTTP response body: {"status":403}
> 
> This occurs when there is no permissions for initialization (in this case, security officer role should be sufficient). We do not have any general way to approach this currently -- global response handling and global exception handling should be addressed together in the pipeline.

If this requires the role "XROAD_SECURITY_OFFICER", then please add this to the reset_security_server.sh" script here:

ROLES='["XROAD_SYSTEM_ADMINISTRATOR"]'

2020-11-30 13:42 UTC, unserializable commented on tests/unit/test_timestamp.py
> +import unittest
Hmm, so what should be done here?

2020-11-30 13:43 UTC, unserializable commented
> Please also update Changelog and User Guide

UG: cf7927e7881fb3fc2edc911550714de18cbe0f79

2020-11-30 13:43 UTC, merged