SSTOOLKIT-101
nordic-institute/X-Road-Security-Server-toolkit pull request #98
Opened 2021-07-13 09:08 UTC by bertofl90

2021-07-13 13:06 UTC, bertvi requested changes

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +| 06.07.2021 | 2.1.4       | Add local groups management                                                  | Alberto Fernandez  |
Date should reflect today

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +            - <SERVICE_CLIENT_ID>
In the configuration file you have "<MEMBER_ID>"

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +* <CLIENT_ID> subsystem client id, e.g. DEV:COM:12345:COMPANY
Do you also support multiple clients or just a single one?

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +The table above shows the following information about the certificates:
"certificates" is wrong here

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +* Access rights: XROAD_SERVICE_ADMINISTRATOR
Don't you need both roles XROAD_SYSTEM_ADMINISTRATOR and XROAD_SERVICE_ADMINISTRATOR here?

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +* Access rights: XROAD_SERVICE_ADMINISTRATOR
Is this single role enough for that operation?

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +id of the service description, e.g. 123, multiple values can also be given, separated by comma, e.g. 123,456
This seems to be some kind of copy-paste and does not belong here?

2021-07-13 13:06 UTC, bertvi commented on docs/xroad_security_server_toolkit_user_guide.md
> +* <SECURITY_SERVER_NAME> seccurity server name, e.g. ss1
"seccurity" should be "security"

2021-07-13 13:06 UTC, bertvi commented on xrdsst/controllers/local_group.py
> +from cement import ex
This file shows 12 PEP8 warnings (your IDE should probably show these on the right as yellow markers)

2021-07-13 13:06 UTC, bertvi commented on xrdsst/controllers/client.py
> +    @staticmethod
This class also seems to have a couple of PEP8 warnings, for example this method does not have a blank line before the other method

2021-07-13 13:27 UTC, bertofl90 commented on docs/xroad_security_server_toolkit_user_guide.md
> +* <CLIENT_ID> subsystem client id, e.g. DEV:COM:12345:COMPANY
it's only prepared for one client each time

2021-07-13 13:50 UTC, bertofl90 commented on docs/xroad_security_server_toolkit_user_guide.md
> +* Access rights: XROAD_SERVICE_ADMINISTRATOR
no only the service administrator

2021-07-13 13:50 UTC, bertofl90 commented on docs/xroad_security_server_toolkit_user_guide.md
> +* Access rights: XROAD_SERVICE_ADMINISTRATOR
yes

2021-07-14 12:21 UTC, bertvi approved these changes

2021-07-14 12:43 UTC, merged